# gateway-server/.github/workflows/deploy.yml

name: CI/CD - Deploy Gateway Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push gateway-server
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: minkeon44883/gateway-server:latest # ⭐️ 이미지 이름 변경

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # === gateway-server 배포 (포트: 8000) ===
            docker pull minkeon44883/gateway-server:latest
            docker stop gateway-server || true
            docker rm gateway-server || true
            docker run -d --name gateway-server -p 8000:8000 \
              -e SPRING_PROFILES_ACTIVE=docker \
              minkeon44883/gateway-server:latest